apiVersion: v1
kind: Secret
metadata:
  name: {{ include "falco-talon.name" . }}-config
  labels:
    {{- include "falco-talon.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    listen_address: {{ default "0.0.0.0" .Values.listenAddress }}
    listen_port: {{ default 2803 .Values.listenPort }}
    watch_rules: {{ default true .Values.watchRules }}
    print_all_events: {{ default false .Values.printAllEvents }}
    deduplication_leader_lease: {{ default true .Values.deduplicationLeaderLease }}
    deduplication_time_window_seconds: {{ default 5 .Values.deduplicationTimeWindowSeconds }}
    default_notifiers: 
    {{- range .Values.defaultNotifiers }}
      - {{ . -}}
    {{ end }}
    notifiers:
    {{- toYaml .Values.notifiers | nindent 6 }}
